name: Train ML Model & Build Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r MLProject/requirements.txt

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager local

      - name: Create Custom Dockerfile for Serving
        run: |
          cat << 'EOF' > MLProject/Dockerfile
          FROM python:3.10-slim
          WORKDIR /app
          COPY requirements.txt .
          RUN pip install --no-cache-dir -r requirements.txt
          COPY . .
          CMD ["python", "modelling.py"]
          EOF

      - name: Upload Model Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/mlruns

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image (Native Mode)
        run: |
          cd MLProject
          docker build -t shavel28/customer-personality-model:latest .

      - name: Push Docker Image to Cloud
        run: |
          docker push shavel28/customer-personality-model:latest
